# Generated by Django 2.1.1 on 2018-10-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
        migrations.RenameModel(
            old_name='Responses',
            new_name='Response',
        ),
    ]
