# Generated by Django 2.1.1 on 2018-10-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20181015_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prompt',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='pid',
            new_name='qid',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='pid',
            new_name='qid',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='pid',
            new_name='qid',
        ),
    ]
