# Generated by Django 2.1.1 on 2018-10-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20181015_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_multi_choice',
            field=models.BooleanField(default=True),
        ),
    ]
