# Generated by Django 2.1.1 on 2018-10-22 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20181021_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
    ]
