# Generated by Django 2.1.1 on 2018-10-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20181022_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='User ID'),
        ),
    ]
