# Generated by Django 2.1.1 on 2018-10-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20181022_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Choice ID'),
        ),
    ]
