# Generated by Django 2.1.1 on 2018-10-23 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20181022_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_multiple_choice',
            field=models.BooleanField(default=True, verbose_name='Is the question multiple choice?'),
        ),
    ]
