# Generated by Django 2.1.1 on 2018-10-23 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20181022_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='sid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Survey ID'),
        ),
    ]
