# Generated by Django 2.1.1 on 2018-10-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20181023_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question', verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey', verbose_name='Survey ID'),
        ),
        migrations.AlterField(
            model_name='response',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question', verbose_name='Question ID'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_text',
            field=models.CharField(max_length=200, verbose_name='Response'),
        ),
    ]
