# Generated by Django 2.1.1 on 2018-10-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20181023_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name_plural': '2. Choices'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': '1. Questions'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name_plural': '3. Responses'},
        ),
    ]
