# Generated by Django 2.1.1 on 2018-10-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20181023_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name_plural': '  Choices'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': ' Questions'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name_plural': '   Responses'},
        ),
    ]
