# Generated by Django 2.1.3 on 2018-12-02 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False, verbose_name='Choice ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='Choice')),
            ],
            options={
                'verbose_name_plural': 'Choices',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False, verbose_name='Email ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False, verbose_name='Question ID')),
                ('question_num', models.IntegerField(default=1, verbose_name='Question Number')),
                ('question_text', models.CharField(max_length=200, verbose_name='Question')),
                ('is_multiple_choice', models.BooleanField(default=True, verbose_name='Is the question multiple choice?')),
                ('allow_multiple', models.BooleanField(default=False, verbose_name='Allow multiple options to be selected?')),
                ('allow_other', models.BooleanField(default=False, verbose_name='Allow users to enter their own choice?')),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False, verbose_name='Response ID')),
                ('userID', models.IntegerField(default=1, verbose_name='User ID')),
                ('response_text', models.CharField(max_length=200, verbose_name='Response')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question', verbose_name='Question ID')),
            ],
            options={
                'verbose_name_plural': 'Responses',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False, verbose_name='Survey ID')),
                ('survey_name', models.CharField(max_length=50, verbose_name='Survey Name')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey', verbose_name='Survey ID'),
        ),
        migrations.AddField(
            model_name='question',
            name='sid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey', verbose_name='Survey ID'),
        ),
        migrations.AddField(
            model_name='choice',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question', verbose_name='Question ID'),
        ),
    ]
