# Generated by Django 2.1.3 on 2018-11-08 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False, verbose_name='Choice ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='Choice')),
            ],
            options={
                'verbose_name_plural': '2. Choices',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False, verbose_name='Question ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='Question')),
                ('is_multiple_choice', models.BooleanField(default=True, verbose_name='Is the question multiple choice?')),
            ],
            options={
                'verbose_name_plural': '1. Questions',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False, verbose_name='Response ID')),
                ('userID', models.IntegerField(default=1)),
                ('response_text', models.CharField(max_length=200, verbose_name='Response')),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question', verbose_name='Question ID')),
            ],
            options={
                'verbose_name_plural': '3. Responses',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False, verbose_name='Survey ID')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='sid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey', verbose_name='Survey ID'),
        ),
        migrations.AddField(
            model_name='choice',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question', verbose_name='Question ID'),
        ),
    ]
