# Generated by Django 2.1.3 on 2018-12-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response_text',
            field=models.CharField(max_length=1000, verbose_name='Response'),
        ),
    ]
