# Generated by Django 2.1.3 on 2018-11-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_response_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='response',
            name='userID',
            field=models.IntegerField(default=1, verbose_name='User ID'),
        ),
    ]
