# Generated by Django 2.1.3 on 2018-11-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_remove_question_allow_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_multiple',
            field=models.BooleanField(default=False, verbose_name='Allow multiple options to be selected?'),
        ),
    ]
