# Generated by Django 2.1.3 on 2018-11-15 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_question_allow_multiple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='allow_multiple',
        ),
    ]
