# Generated by Django 2.1.3 on 2018-11-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20181119_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='sid',
        ),
    ]
